### ISSUE TITLE
client.logout() bug

### ISSUE THREAD

**Issue by LKAYHot** [FabioGaming/Amino.NET#29]
When I use client.logout(); I get this 
![image](https://github.com/Amino-NET-Group/Amino.NET/assets/128542643/c0ed5be8-8927-4499-bb5c-2f4c0e027737)
I use it after client.login() (login is correct, because I can check information about profile). I was trying simple await, but nothing has changed.

**Comment by FabioGaming** [comment]
Is your client logged into an account before you call the logout method?

**Comment by LKAYHot** [comment]
![image](https://github.com/Amino-NET-Group/Amino.NET/assets/128542643/8c9e1d7d-f004-4ee0-81c3-bf1c458ecbbc)
Yes

**Comment by FabioGaming** [comment]
I've given this thread the Bug tag until further updates

**Comment by FabioGaming** [comment]
This issue is fixed with #31 
You can download Amino.NET version 1.7.0-dev0.2.0 from NuGet in order for it to work while no stable new release is out yet
