### ISSUE TITLE
delete_message is not working, issue with JSON

### ISSUE THREAD

**Issue by athype** [FabioGaming/Amino.NET#34]
Cannot delete messages, neither as staff, nor as non-staff, results in exception. Issue can be because duplicate key.

![Screenshot 2024-05-19 233441](https://github.com/Amino-NET-Group/Amino.NET/assets/61124362/c8ed27dc-a40a-413a-822d-ee8840185b94)
![error for bot2](https://github.com/Amino-NET-Group/Amino.NET/assets/61124362/fe17e43c-2c05-4852-925d-1ddf60d78fdb)
![error for bot](https://github.com/Amino-NET-Group/Amino.NET/assets/61124362/35ef39d3-6f07-4d81-9375-886fe0bc93ff)

**Comment by FabioGaming** [comment]
Added to the bug list, will be fixed on the next patch branch, will mention the issue

**Comment by FabioGaming** [comment]
issue should be fixed with #37 and is available on the latest dev build
