### ISSUE TITLE
client.get_community_info(cid); issue

### ISSUE THREAD

**Issue by LKAYHot** [FabioGaming/Amino.NET#38]
When I'm trying to write information from community in variable, it throws me an exception:
**The JSON value could not be converted to System.String. Path: $.themePack.themePackRevision | LineNumber: 0 | BytePositionInLine: 945."**

Example:
```
Amino.Client client = new Amino.Client();
await client.login(email, password);
await client.join_community(cid);
var community = client.get_community_info(cid); // exception, cid is correct, because join works perfectly.
```

**Comment by FabioGaming** [comment]
fixed in #41 and availave in 1.7.0-dev0.2.3
